Revert "compat: backport skb_try_make_writable"
This reverts commit 3511eb3b431d1da806a27f3b7bb25b4b119df827.
build error: ../net/sched/sch_cake/cobalt_compat.h:100:19: error: redefinition of 'skb_try_make_writable'
static inline int skb_try_make_writable(struct sk_buff *skb,
                  ^
../include/linux/skbuff.h:2573:19: note: previous definition is here
static inline int skb_try_make_writable(struct sk_buff *skb,
                  ^
2 errors generated.